<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/07 07:21:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=upgrader',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
