<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/07 07:34:43

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=express_hrm',
  'username' => 'admin',
  'password' => 'admin123',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
